### ISSUE TITLE
igc vlan doesn't work

### ISSUE THREAD

**Issue by csantanapr** [ibm-garage-cloud/ibm-garage-cloud-cli#13]
Install `igc`
```
npm i -g @ibmgaragecloud/cloud-native-toolkit-cli
```

Login into ibmcloud cli

Run the command
```
igc vlan -h
⠼ Getting zones
```
exits with `1`
```
echo $?
1
```

version `0.4.8`
```
0.4.8
```

**Comment by seansund** [comment]
Enhance to be smarter and more interactive

**Comment by davesteinberg** [comment]
@seansund Is this a matter of enhancement, or is it just plain broken? Is it currently working for you? I seem to recall that it worked fine before and now it's just crashing for me, as @csantanapr describes.

**Comment by davesteinberg** [comment]
Oh, I just saw #9. Isn't this just a dupe of that?
