### ISSUE TITLE
igc pipeline --tekton Error getting cluster_type

### ISSUE THREAD

**Issue by csantanapr** [ibm-garage-cloud/ibm-garage-cloud-cli#15]
Using OpenShift 4.3 on CRC or IBM Cloud

Using the node typescript template
```
igc pipeline --tekton
Error getting cluster_type from configMap `ibmcloud-config`. Attempting to retrieve it from the secret
Error getting cluster_type from secret `ibmcloud-apikey`. Defaulting to `kubernetes`
Getting git parameters
  Project git repo: https://github.com/csantanapr/ibm-garage-cloud-cli.git
```

**Comment by csantanapr** [comment]
After continue I get the following at tne end
```
Error registering pipeline: configmaps "ibmcloud-config" not found
``
```
Getting git parameters
  Project git repo: https://github.com/csantanapr/ibm-garage-cloud-cli.git
? Provide the username: csantanapr
? Provide your password/personal access token: [hidden]
? Provide the branch the pipeline should use: master
Setting up dev namespace
Checking for existing namespace: dev
Setting up pull secrets
Setting up tls secrets
Adding pull secrets to serviceAccount
Copying ConfigMaps
Copying Secrets
Copying Tekton tasks
Copying Tekton pipelines
Copying Jenkins credentials
Creating service account: pipeline
Creating Git PipelineResource
Creating Image PipelineResource
Error registering pipeline: configmaps "ibmcloud-config" not found
```

**Comment by seansund** [comment]
For some reason, `ibmcloud-config` is not getting copied into the `tools` namespace. The `ibmcloud-config` configmap gets created in the default namespace and at some point would get copied into the other namespaces. 

The `tools` namespace is seen as the source for everything by the and it is only looking there. Either we need to make sure the configmap gets copied into the tools namespace during the terraform process and/or the CLI should look in the default namespace for it.

**Comment by csantanapr** [comment]
Somehow terraform didn't create `ibmcloud-config` in `tools`

**Comment by csantanapr** [comment]
ah is in the `default` namespace but not in the `tools`

**Comment by seansund** [comment]
It looks like it may be a timing issue in the terraform. Works fine for IKS and OCP3 but not OCP4. I'm testing a fix now for that.

We could have `igc pipeline` and/or `igc namespace` look for the configmap in the default namespace if it can't find it in the tools namespace then copy it into tools

**Comment by seansund** [comment]
You can manually copy it into `tools` as a workaround

**Comment by csantanapr** [comment]
yes that's what I did as workaround
