### ISSUE TITLE
igc pipeline --tekton should not do anything with jenkins

### ISSUE THREAD

**Issue by csantanapr** [ibm-garage-cloud/ibm-garage-cloud-cli#17]
Using OpenShift 4
run igc pipeline --tekton
problem a jenkins message is printed, it should not assume we have jenkins installed

```
Copying Jenkins credentials
```

To reproduce
```
igc pipeline --tekton
Error getting cluster_type from configMap `ibmcloud-config`. Attempting to retrieve it from the secret
Error getting cluster_type from secret `ibmcloud-apikey`. Defaulting to `kubernetes`
Getting git parameters
  Project git repo: https://github.com/csantanapr/ibm-garage-cloud-cli.git
? Provide the username: csantanapr
? Provide your password/personal access token: [hidden]
? Provide the branch the pipeline should use: master
Setting up dev namespace
Checking for existing namespace: dev
Setting up pull secrets
Setting up tls secrets
Adding pull secrets to serviceAccount
Copying ConfigMaps
Copying Secrets
Copying Tekton tasks
Copying Tekton pipelines
Copying Jenkins credentials
Creating service account: pipeline
Creating Git PipelineResource
Creating Image PipelineResource
Error registering pipeline: configmaps "ibmcloud-config" not found
```

**Comment by seansund** [comment]
What's happening is that the `pipeline` command calls the logic for the `namespace` command. The `namespace` logic is dumb in that it doesn't know, or care if you are using Tekton or Jenkins. It just tries to copy everything it knows about, which includes the Jenkins credentials, the Tekton tasks, and the pipeline service account.

We need to add some more smarts into the namespace logic (or less logging)

**Comment by seansund** [comment]
Related to ibm-garage-cloud/ibm-garage-cloud-cli#17

**Comment by seansund** [comment]
We are overhauling the flow and use of `igc namespace` and `igc pipeline`. This issue will be addressed in those changes
